backend:
  name: auth0
  login: true
  auth0:
    domain: dev-60n23r4dd7ykzah3.us.auth0.com
    client_id: sUgA2CwFyxsuXPXq6XUGQ5840OLUABsB

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

