backend:
  name: git-gateway
  branch: master # Branche sur laquelle Netlify CMS va interagir

media_folder: "static/images" # Dossier où seront stockées les images
public_folder: "/images"     # Dossier public accessible depuis l'URL

collections:
  - name: "blog" # Nom de la collection (exemple)
    label: "Blog" # Nom affiché dans l'interface CMS
    folder: "content/blog" # Dossier où les fichiers sont stockés dans ton repo
    create: true # Permet la création de nouveaux articles
    fields:
      - { label: "Title", name: "title", widget: "string" } # Champ titre
      - { label: "Body", name: "body", widget: "markdown" } # Champ contenu (Markdown)
