backend:
  name: auth0
  auth0:
    client_id: sUgA2CwFyxsuXPXq6XUGQ5840OLUABsB # Remplace par ton CLIENT_ID Auth0
    client_secret: TON_CLIENT_SECRET # Remplace par ton SECRET Auth0
    domain: dev-60n23r4dd7ykzah3.us.auth0.com # Remplace par ton DOMAIN Auth0
  branch: master
nano public/admin/config.yml
backend:
  name: git-gateway
  branch: master # Branche sur laquelle Netlify CMS va interagir

media_folder: "static/images" # Dossier où sebackend:
  name: git-gateway
  branch: master # Branche sur laquelle Netlify CMS va interagir

media_folder: "static/images" # Dossier où seront stockées les images
public_folder: "/images"     # Dossier public accessible depuis l'URL

collections:
  - name: "blog" # Nom de la collection (exemple)
    label: "Blog" # Nom affiché dans l'interface CMS
    folder: "content/blog" # Dossier où les fichiers sont stockés dans ton repo
    create: true # Permet la création de nouveaux articles
    fields:
      - { label: "Title", name: "title", widget: "string" } # Champ titre
      - { label: "Body", name: "body", widget: "markdown" } # Champ contenu (Markdown)
